<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Update="datos_prueba.xml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="datos_actualizacion.xml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="datos_imposible.xml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="datos_dinamicos.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
